name: Python checks

on:
  push:
    branches: [ develop, main ]
    paths:
      - "**/*.py"
      - "requirements.txt"
      - "pyproject.toml"
      - ".github/workflows/python_checks.yml"
  pull_request:
    branches: [ develop, main ]
    paths:
      - "**/*.py"
      - "requirements.txt"
      - "pyproject.toml"
      - ".github/workflows/python_checks.yml"

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # herramientas de calidad
          pip install ruff==0.5.7 black==24.8.0 isort==5.13.2 mypy==1.10.0 bandit==1.7.9 pytest==8.3.2

      - name: Ruff (lint)
        run: ruff check .

      - name: Black (formato)
        run: black --check .

      - name: isort (imports)
        run: isort --check-only .

      - name: Mypy (tipado) — permisivo
        continue-on-error: true
        run: mypy --ignore-missing-imports .

      - name: Bandit (seguridad)
        run: bandit -r . -x tests

      - name: Pytest (si hay tests)
        if: ${{ hashFiles('tests/**') != '' }}
        run: pytest -q
